### PR TITLE
#11 seach cocktail name

### LINKED ISSUE #11: Search by cocktail name
- [ ] test API in postman
- [ ] configure to search by a cocktail name

### PR DESCRIPTION
**Pull request by AshleyLerma**
resolved #11

### CODE REVIEW

**Comment by AshleyLerma** [comment]
We created an html page for the search by cocktail name functionality

**Review by juanlajara — APPROVED** [review]
I was there when it happened - approved :)

**Review by joshuabogart — APPROVED** [review]
Looks awesome!!!!!!!!! Tommys Marita is going to be amazing

**Review by Cranekick50 — APPROVED** [review]
Great job guys

**Review by Frazerhughes — APPROVED** [review]

**Pull request merged**
